use crate::db::schema::{base_forms, synonym_groups, word_in_group};
use diesel::prelude::*;

// Generated by diesel_ext

#[derive(Queryable, Debug, Identifiable)]
#[diesel(table_name = base_forms)]
#[diesel(primary_key(word_id, base_form_id))]
pub struct BaseForm {
    pub word_id: i32,
    pub base_form_id: i32,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(table_name = synonym_groups)]
#[diesel(primary_key(group_id))]
pub struct SynonymGroup {
    pub group_id: i32,
    pub group_meaning: String,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(table_name = word_in_group)]
#[diesel(primary_key(word_id, group_id))]
pub struct WordInGroup {
    pub word_id: i32,
    pub group_id: i32,
}

#[derive(Queryable, Debug)]
#[diesel(table_name = words)]
pub struct Word {
    pub id: i32,
    pub word: String,
}
