name: publish

on:
  workflow_dispatch:

jobs:
  publish-tauri-windows:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5

      - name: setup bun
        uses: oven-sh/setup-bun@v2

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: install frontend dependencies
        run: bun install

      - name: download database
        run: |
          curl -L -o database.sqlite `
            "https://github.com/Leon135/Synonik-db-builder/releases/latest/download/database.sqlite"

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__
          releaseName: "Synonik v__VERSION__"
          releaseBody: "See the assets below to download and install."
          releaseDraft: true
          prerelease: false

  publish-tauri-linux:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5

      - name: install dependencies (ubuntu only)
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf xdg-utils libfuse2 file

      - name: setup bun
        uses: oven-sh/setup-bun@v2

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install frontend dependencies
        run: bun install

      - name: download database
        run: |
          curl -L -o database.sqlite \
            "https://github.com/Leon135/Synonik-db-builder/releases/latest/download/database.sqlite"

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__
          releaseName: "Synonik v__VERSION__"
          releaseBody: "See the assets below to download and install."
          releaseDraft: true
          prerelease: false
          args: --bundles appimage
