name: publish

on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup bun
        uses: oven-sh/setup-bun@v2

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: install frontend dependencies
        run: bun install

      - name: download database
        run: |
          curl -L -o database.sqlite `
            "https://github.com/Leon135/Synonik-db-builder/releases/download/latest/database.sqlite"

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__
          releaseName: "Synonik v__VERSION__"
          releaseBody: "See the assets below to download and install."
          releaseDraft: true
          prerelease: false
